name: Build skulpt-pygame-zero

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: "0.3.4"
        description: "The version for this release."

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Pack
        run: npm pack
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          files: "skulpt-pygame-zero-${{ inputs.tag }}.tgz"
